### ISSUE TITLE
"too much recursion" with certain inputs

### ISSUE THREAD

**Issue by netthier** [EmNudge/logpipe#63]
I tried viewing some large logs (>1k lines), but after a few seconds of loading the website mostly stayed empty, and logged this:
```
Uncaught (in promise) InternalError: too much recursion
    replacePath http://localhost:37647/highlight.js:155
    highlightText http://localhost:37647/highlight.js:205
    getLogEl http://localhost:37647/index.js:42
    onmessage http://localhost:37647/index.js:86
    onmessage http://localhost:37647/index.js:86
```
It also shows a line count, albeit incorrect, but no lines:
![image](https://github.com/EmNudge/logpipe/assets/66856670/0c57bbd0-bfdc-4b29-8ebb-10ee38e8b6d5)

(Firefox 124.0.1, NixOS, Node v21.7.1)

**Comment by netthier** [comment]
Seems unrelated to large inputs, minimal reproducer:
```
$ echo "2024-04-16 18:57:31.109 2024-04-16 16:57:31 INFO     foo_bar_baz_kek_quz_buz99999999 timeseries received from ur mom, waited 0.159274 seconds." | ./node_modules/.bin/logpipe
```

**Comment by EmNudge** [comment]
I've isolated it further to `foo_bar_baz_kek_quz_buz99999999`

**Comment by EmNudge** [comment]
Can you test with the latest build? 
I found a regex in the path parsing that was exponential for certain inputs. It might have been the one.

**Comment by EmNudge** [comment]
Fixed the earlier issue for many inputs, but still have a problem for the following input:
```sh
/tmp/foo_bar_baz_1234567890.sock
```
<img width="1003" alt="image" src="https://github.com/EmNudge/logpipe/assets/24513691/c2a25b37-2e11-4f25-a5cd-45d86a588aed">

We can change this regex to `\/?(?:[\w.-]+\/)+(\S+)` which matches the functionality well and doesn't have this issue. 

Will try to roll out another fix tonight

**Comment by netthier** [comment]
I can confirm that the issue no longer occurs in the latest versions with my inputs.
