### ISSUE TITLE
Make link to video in README stand out more

### ISSUE THREAD

**Issue by Ytrog** [EmNudge/logpipe#9]
As I mentioned on the [reddit thread about it](https://www.reddit.com/r/programming/s/0yry7fbhcH) make the video stand out more in the README. I didn't know to look for it and only your comment on reddit made me look.

**Comment by EmNudge** [comment]
Is it possible you're not viewing the repo on github directly?

It is just a link, but that seems to be how github prefers video embeds to work. It looks like this on my screen. Does it look different for you?

![image](https://github.com/EmNudge/logpipe/assets/24513691/4e04052f-ce32-4168-a1ed-c9a55d5d1903)

**Comment by Ytrog** [comment]
![Screenshot_20240408_213445_GitHub.jpg](https://github.com/EmNudge/logpipe/assets/2880376/f24d661e-6b3c-47d9-9c12-1cd46cb74bab)

I use the official Android app for GitHub on my phone 🤔

**Comment by EmNudge** [comment]
Yeah, it seems the github app generally has much worse support for readme features. I've seen it fail with syntax highlighting as well. The website directly works, however.

I can look into updating it somehow to make it more obvious, although this is generally more of a Github App issue than anything.

**Comment by Ytrog** [comment]
Yeah, you're right. I didn't realize until now sadly.

If you want you can add a header above with `# video` or something like that. Otherwise just close the issue.

**Comment by EmNudge** [comment]
I put it in a video tag, which github seems to render the same. This does hide the video on mobile, but at least it's not a stray link. I may consider adding a general image for github mobile users in the future (although again, this is definitely a bug with Github Mobile)
